blank_issues_enabled: false
contact_links:
  - name: Feature Requests
    url: https://features.metamanager.wiki
    about: Please use the features site to submit and vote on features.
  - name: Plex Meta Manager Wiki
    url: https://metamanager.wiki
    about: Please check the wiki to see if your question has already been answered.
  - name: Discord
    url: https://discord.gg/plexmetamanager
    about: Please use the Plex Meta Manager Discord to ask for support.
