libraries:
  Movies:
    operations:
      assets_for_all: true
    overlay_path:
      - remove_overlays: false
      - pmm: resolution
      - pmm: video_format
        template_variables:
          horizontal_align: center
          vertical_align: top
      - pmm: versions
  Shows:
    operations:
      assets_for_all: true
    overlay_path:
      - remove_overlays: false
      - pmm: video_format
        template_variables:
          overlay_level: season
          horizontal_align: center
          vertical_align: top
      - pmm: resolution
      - pmm: resolution
        template_variables:
          overlay_level: season
      - pmm: resolution
        template_variables:
          overlay_level: episode
      - pmm: video_format
        template_variables:
          overlay_level: episode
      - pmm: episode_info
        template_variables:
          overlay_level: episode
          vertical_offset: 30
      - pmm: versions
        template_variables:
          builder_level: episode
  Anime:
    operations:
      assets_for_all: true
    metadata_path:
      - file: config/custom/Monogatari.yml
    overlay_path:
      - remove_overlays: false
      - pmm: video_format
        template_variables:
          overlay_level: season
          horizontal_align: center
          vertical_align: top
      - pmm: resolution
      - pmm: resolution
        template_variables:
          overlay_level: season
      - pmm: resolution
        template_variables:
          overlay_level: episode
      - pmm: video_format
        template_variables:
          overlay_level: episode
      - pmm: episode_info
        template_variables:
          overlay_level: episode
          vertical_offset: 30
      - pmm: versions
        template_variables:
          builder_level: episode
settings:
  cache: true
  cache_expiration: 60
  asset_directory: /data/Posters
  asset_folders: true
  asset_depth: 2
  create_asset_folders: false
  prioritize_assets: true
  dimensional_asset_rename: false
  download_url_assets: false
  show_missing_season_assets: false
  show_missing_episode_assets: false
  show_asset_not_needed: false
  sync_mode: append
  minimum_items: 1
  default_collection_order: release
  delete_below_minimum: true
  delete_not_scheduled: false
  run_again_delay: 2
  missing_only_released: false
  only_filter_missing: false
  show_unmanaged: true
  show_unconfigured: true
  show_filtered: true
  show_options: true
  show_missing: false
  show_missing_assets: true
  save_report: false
  tvdb_language: eng
  ignore_ids:
  ignore_imdb_ids:
  item_refresh_delay: 0
  playlist_sync_to_user: all
  playlist_exclude_users:
  playlist_report: false
  verify_ssl: true
  custom_repo:
  check_nightly: false
  webhooks: # Can be individually specified per library as well
  error:
  version:
  run_start:
  run_end:
  changes:
  delete:
plex: # Can be individually specified per library as well; REQUIRED for the script to run
  url: http://127.0.0.1:32400
  token: xUfLv_78reC19knbqNPm
  timeout: 60
  clean_bundles: false
  empty_trash: false
  optimize: false
  db_cache:
tmdb: # REQUIRED for the script to run
  apikey: 50b87e910c68390b41b972ad3b174917
  language: en
  cache_expiration: 60
  region:
